name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:

    - name: Setup Flutter ${{ matrix.flutter-version }}
      id: flutter
      if: "!startsWith(matrix.bot, 'dart')"
      uses: DanTup/gh-actions/setup-flutter@master
      with:
        channel: ${{ matrix.flutter-version }}
    
    - run: flutter update-packages
      if: matrix.bot == 'flutter_repo'
      
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
      - name: Setup Dart ${{ matrix.dart-version }}
      uses: DanTup/gh-actions/setup-dart@master
      with:
        channel: ${{ matrix.dart-version }}
    
    - name: Print Dart version
      run: dart --version

    - name: Print Flutter version
      if: "!startsWith(matrix.bot, 'dart')"
      run: flutter --version